In [1]:
import numpy as np

In [3]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [4]:
a.shape

(2, 7)

In [5]:
a.size

14

In [11]:
# get specific element [ r ,c]
a[1, 5]

13

In [14]:
# get specific row [ r ]
a[0 ,:]

array([1, 2, 3, 4, 5, 6, 7])

In [16]:
# get specific column 
a[:,4]

array([ 5, 12])

In [19]:
# geting little more fancy [startindex:endindex:stepsize]
a[1,1:6:2]

array([ 9, 11, 13])

In [22]:
a[1,6] = 20
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 20]])

In [24]:
a[ :, 6] = [7,14]
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [27]:
a[0, :] = [8,9,10,11,12,13,14]
a

array([[ 8,  9, 10, 11, 12, 13, 14],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [31]:
a[0,0:3] = [1,2,3]
a

array([[ 1,  2,  3, 11, 12, 13, 14],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [36]:
a[0,3:] = [4,5,6,7]
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [39]:
'''3d example'''

'3d example'

In [ ]:
b = np.array