In [13]:
import numpy as np

In [15]:
# all zeros matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
# all 1s matrix

np.ones((2,3),dtype = "int32")

array([[1, 1, 1],
       [1, 1, 1]])

In [12]:
# any other no
np.full((2,4), 99)

array([[99, 99, 99, 99],
       [99, 99, 99, 99]])

In [17]:
# random decimal no
np.random.rand(4,2)

array([[0.43106616, 0.23796601],
       [0.56415276, 0.92531916],
       [0.00927625, 0.10975837],
       [0.96207036, 0.89355918]])

In [21]:
# random interger no
np.random.randint(7,size = (3,3))

array([[5, 4, 5],
       [0, 0, 5],
       [6, 4, 1]])

In [22]:
# the identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])