In [1]:
import numpy as np

In [3]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [4]:
a + 2

array([3, 4, 5, 6])

In [5]:
a - 2

array([-1,  0,  1,  2])

In [6]:
a * 2

array([2, 4, 6, 8])

In [7]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [8]:
# take the sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [9]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [10]:
#### linear algebra

In [11]:
 a = np.ones((2,3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [13]:
b = np.full((3,2),2)
b

array([[2, 2],
       [2, 2],
       [2, 2]])

In [14]:
# matmul to multiple the matrix
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [16]:
# find the detriminent
c = np.array([[1,-2,3],[2,0,3],[1,5,4]])
c

array([[ 1, -2,  3],
       [ 2,  0,  3],
       [ 1,  5,  4]])

In [17]:
np.linalg.det(c)

24.999999999999996